/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import servicios.Simca.Estudiante;
import servicios.Simca.ServicioSimcaImpl;
import servicios.Simca.ServicioSimcaImpl_Service;
import servicios.biblioteca.Libro;
import servicios.biblioteca.Prestamo;
import servicios.biblioteca.ServicioBibliotecaImpl;
import servicios.biblioteca.ServicioBibliotecaImpl_Service;
import servicios.recursosHumanos.Personal;
import servicios.recursosHumanos.ServicioRecursosHumanosImpl;
import servicios.recursosHumanos.ServicioRecursosHumanosImpl_Service;


/**
 *
 * @author VICTOR MANUEL
 */
public class GUIPrestamos extends javax.swing.JFrame {
    private ServicioSimcaImpl_Service referenciaAlServicioSimca;
    private ServicioSimcaImpl objServicioWebSimca;
    private ServicioRecursosHumanosImpl_Service referenciaAlServicioRecHumanos;
    private ServicioRecursosHumanosImpl objServicioWebRecHumanos;
    private ServicioBibliotecaImpl_Service referenciaAlServicioBiblioteca;
    private ServicioBibliotecaImpl objServicioWebBiblioteca;
    Estudiante estudiante = null;
    Personal personal = null;
    Libro libro = null;
    DefaultTableModel modelo;
    DefaultTableModel modeloPrestamos;
    CardLayout cardLayout;
    int boton;
    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form GUIPrestamos
     */
    public GUIPrestamos() {
        this.setContentPane(fondo);
        initComponents();
        jDateChooser1.setMinSelectableDate(new Date());
        cardLayout = (CardLayout) (jPanelCardLayout.getLayout());
        modelo = (DefaultTableModel) jTable1.getModel();
        modeloPrestamos = (DefaultTableModel) jTablePrestamosPendientes.getModel();
        setLocationRelativeTo(null);
        referenciaAlServicioSimca= new ServicioSimcaImpl_Service() ;
        objServicioWebSimca= referenciaAlServicioSimca.getServicioSimcaImplPort();
        referenciaAlServicioRecHumanos= new ServicioRecursosHumanosImpl_Service() ;
        objServicioWebRecHumanos= referenciaAlServicioRecHumanos.getServicioRecursosHumanosImplPort();
        referenciaAlServicioBiblioteca= new ServicioBibliotecaImpl_Service() ;
        objServicioWebBiblioteca= referenciaAlServicioBiblioteca.getServicioBibliotecaImplPort();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelCardLayout = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEstudiante = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonPrestamo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new FondoPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonCC = new javax.swing.JRadioButton();
        jRadioButtonPP = new javax.swing.JRadioButton();
        jTextFieldIdPersonal = new javax.swing.JTextField();
        jButtonAceptarPersonal = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPersonal = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButtonPrestamoPersonal = new javax.swing.JButton();
        jPanel1 = new FondoPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePrestamosPendientes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButtonListar = new javax.swing.JButton();
        jPanelBuscarLibro = new FondoPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonRegistrarPrestamo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCardLayout.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(189, 0, 0));
        jLabel1.setText("Estudiante");

        jTextFieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese codigo del estudiante");

        jTextAreaEstudiante.setEditable(false);
        jTextAreaEstudiante.setColumns(20);
        jTextAreaEstudiante.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEstudiante);

        jButtonPrestamo.setText("Buscar libro");
        jButtonPrestamo.setEnabled(false);
        jButtonPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrestamoActionPerformed(evt);
            }
        });

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Informacion del estudiante activo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAceptar)
                                .addGap(30, 30, 30))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrestamo)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel6)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrestamo)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estudiante", jPanel2);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 17, 17));
        jLabel2.setText("Administrativo o docente");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de identificacion");

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de identificacion");

        buttonGroup1.add(jRadioButtonCC);
        jRadioButtonCC.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jRadioButtonCC.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCC.setText("CC");

        buttonGroup1.add(jRadioButtonPP);
        jRadioButtonPP.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jRadioButtonPP.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonPP.setText("PP");

        jTextFieldIdPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdPersonalKeyTyped(evt);
            }
        });

        jButtonAceptarPersonal.setText("Aceptar");
        jButtonAceptarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarPersonalActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Informacion del administrativo o docente activo");

        jTextAreaPersonal.setEditable(false);
        jTextAreaPersonal.setColumns(20);
        jTextAreaPersonal.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPersonal);

        jButton2.setText("salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonPrestamoPersonal.setText("Buscar Libro");
        jButtonPrestamoPersonal.setEnabled(false);
        jButtonPrestamoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrestamoPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrestamoPersonal))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButtonCC)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAceptarPersonal)
                        .addGap(43, 43, 43))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButtonAceptarPersonal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButtonCC)
                            .addComponent(jRadioButtonPP))))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrestamoPersonal)
                    .addComponent(jButton2)))
        );

        jTabbedPane1.addTab("Personal", jPanel3);

        jTablePrestamosPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tipo_Usuario", "tipo_id", "Id", "Nombres", "Apellidos", "Titulo Libro", "Autor Libro", "Fecha"
            }
        ));
        jTablePrestamosPendientes.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jTablePrestamosPendientes);

        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(201, 3, 3));
        jLabel11.setText("Prestamos pendientes");

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jButtonListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel1);

        jPanelCardLayout.add(jTabbedPane1, "cardUsuario");

        jPanelBuscarLibro.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Buscar Libro");

        jLabel9.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrese titulo del libro");

        jLabel10.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrese autor del libro");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButtonRegistrarPrestamo.setText("Registrar prestamo");
        jButtonRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPrestamoActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingrese una fecha de devolucion");

        jLabel13.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Seleccione un libro");

        javax.swing.GroupLayout jPanelBuscarLibroLayout = new javax.swing.GroupLayout(jPanelBuscarLibro);
        jPanelBuscarLibro.setLayout(jPanelBuscarLibroLayout);
        jPanelBuscarLibroLayout.setHorizontalGroup(
            jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLibroLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarPrestamo)
                .addGap(94, 94, 94))
            .addGroup(jPanelBuscarLibroLayout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanelBuscarLibroLayout.createSequentialGroup()
                .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarLibroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBuscarLibroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscarLibroLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLibroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLibroLayout.createSequentialGroup()
                        .addComponent(jButtonBuscar)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLibroLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(107, 107, 107))))
        );
        jPanelBuscarLibroLayout.setVerticalGroup(
            jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(47, 47, 47)
                .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButtonRegistrarPrestamo))
                .addContainerGap())
        );

        jPanelCardLayout.add(jPanelBuscarLibro, "cardBuscarLibro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldCodigo.getText().equals("")){
            estudiante = objServicioWebSimca.estaActivo(Integer.parseInt(jTextFieldCodigo.getText()) );
            jTextAreaEstudiante.setText("");
            if(estudiante != null){
                jTextAreaEstudiante.append("Codigo: "+estudiante.getCodigo()+"\n");
                jTextAreaEstudiante.append("Identificacion"+estudiante.getIdentificacion()+"\n");
                jTextAreaEstudiante.append("Nombres: "+estudiante.getNombres()+"\n");
                jTextAreaEstudiante.append("Apellidos"+estudiante.getApellidos()+"\n");
                jButtonPrestamo.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "El estudiante no esta activo");
                jButtonPrestamo.setEnabled(false);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No se permite campos vacios");
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAceptarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarPersonalActionPerformed
        // TODO add your handling code here:
        String tipo_id = null;
        if (jRadioButtonCC.isSelected()) {
            tipo_id = "CC";
        }
        if (jRadioButtonPP.isSelected()) {
            tipo_id = "PP";
        }
        if(!jTextFieldIdPersonal.getText().equals("") && tipo_id != null){
            personal = objServicioWebRecHumanos.personalActivo(tipo_id,Integer.parseInt(jTextFieldIdPersonal.getText()) );
            jTextAreaPersonal.setText("");
            if(personal != null){
                jTextAreaPersonal.append(personal.getTipoPersonal()+"\n");
                jTextAreaPersonal.append("Tipo identificacion: "+personal.getTipoId()+"\n");
                jTextAreaPersonal.append("Identificacion"+personal.getIdentificacion()+"\n");
                jTextAreaPersonal.append("Nombres: "+personal.getNombres()+"\n");
                jTextAreaPersonal.append("Apellidos"+personal.getApellidos()+"\n");
                jButtonPrestamoPersonal.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "El personal no esta activo");
                jButtonPrestamoPersonal.setEnabled(false);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
        }
    }//GEN-LAST:event_jButtonAceptarPersonalActionPerformed

    private void jButtonPrestamoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrestamoPersonalActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelCardLayout, "cardBuscarLibro");
        boton = 2;
    }//GEN-LAST:event_jButtonPrestamoPersonalActionPerformed

    private void jButtonPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrestamoActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelCardLayout, "cardBuscarLibro");
        boton = 1;
    }//GEN-LAST:event_jButtonPrestamoActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:
        limpiarPrestamos();
        List<Prestamo> prestamosPendientes;
        prestamosPendientes = objServicioWebBiblioteca.prestamosPendientes();
        for(Prestamo p:prestamosPendientes){
            modeloPrestamos.addRow(new Object[] {p.getUsuario().getTipoUsuario(), p.getUsuario().getTipoId(), p.getUsuario().getIdentificacion(),p.getUsuario().getNombres(),p.getUsuario().getApellidos(),
            p.getLibro().getTitulo(),p.getLibro().getAutor(),p.getFecha()});
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jTextFieldIdPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdPersonalKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            //getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIdPersonalKeyTyped

    private void jTextFieldCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            //getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodigoKeyTyped

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        limpiarBuscarLibros();
        ArrayList<Libro> libros;
        libros = (ArrayList<Libro>) objServicioWebBiblioteca.buscarLibro(jTextFieldTitulo.getText(), jTextFieldAutor.getText());
        for (Libro l: libros) {
            modelo.addRow(new Object[] {l.getTitulo(),l.getAutor()});
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelCardLayout, "cardUsuario");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPrestamoActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        try{
            Date date = new Date();
            String fechaComoCadena = sdf.format(jDateChooser1.getDate());
            int fila = jTable1.getSelectedRow();
            if(fila == -1){
                JOptionPane.showMessageDialog(null, "Seleccione un libro");
            }else{
                libro = new Libro();
                libro.setTitulo((String) modelo.getValueAt(fila, 0));
                libro.setAutor((String) modelo.getValueAt(fila, 1));

                boolean bandera;
                if(boton == 1){
                    bandera = objServicioWebBiblioteca.registrarPrestamo("Estudiante",libro, estudiante.getTipoId(), estudiante.getIdentificacion(), estudiante.getNombres(), estudiante.getApellidos(), fechaComoCadena);
                }else{
                    bandera = objServicioWebBiblioteca.registrarPrestamo(personal.getTipoPersonal(), libro, personal.getTipoId(), personal.getIdentificacion(), personal.getNombres(), personal.getApellidos(), fechaComoCadena);

                }
                if(bandera){
                    JOptionPane.showMessageDialog(null, "Se registro prestamo correctamente");
                    cardLayout.show(jPanelCardLayout, "cardUsuario");

                }else
                JOptionPane.showMessageDialog(null, "No se realizo el prestamo");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese fecha de devolucion.");
        }
    }//GEN-LAST:event_jButtonRegistrarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAceptarPersonal;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonPrestamo;
    private javax.swing.JButton jButtonPrestamoPersonal;
    private javax.swing.JButton jButtonRegistrarPrestamo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBuscarLibro;
    private javax.swing.JPanel jPanelCardLayout;
    private javax.swing.JRadioButton jRadioButtonCC;
    private javax.swing.JRadioButton jRadioButtonPP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablePrestamosPendientes;
    private javax.swing.JTextArea jTextAreaEstudiante;
    private javax.swing.JTextArea jTextAreaPersonal;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldIdPersonal;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

public void limpiarPrestamos(){
    for (int i = modeloPrestamos.getRowCount() - 1; i >= 0; i--) {
        modeloPrestamos.removeRow(i);
    }   
}

    private void limpiarBuscarLibros() {
        for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }   
    }
    class FondoPanel extends JPanel{
        private Image imagenFondo;
        @Override
        public void paint(Graphics g){
            imagenFondo = new ImageIcon(getClass().getResource("/imagenes/fondoUnicauca.png")).getImage();
            g.drawImage(imagenFondo, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
